name: flutter_lunch_menu_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  json_annotation: ^4.8.0
  shared_preferences: ^2.1.0
  easy_localization: ^3.0.1
  package_info_plus: ^3.1.0
  store_redirect: ^2.0.1
  url_launcher: ^6.1.10
  flutter_native_splash: ^2.2.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.0"
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  flutter_oss_licenses: ^2.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/translations/

flutter_native_splash:
  image: assets/app_icon.png
  color: "#2e2e2e"

  android_12:
    image: assets/app_icon.png
    color: "#2e2e2e"

  android: true
  ios: false
  web: false