# Spring Boot configuration

# Set active profile
spring:
  config:
    activate:
      on-profile: "dev"

---

spring:
  profiles:
    active: default

  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    open-in-view: true

# Logger configuration
logging:
  file:
    path: "./logs"
  level:
    org.springframework: info
    org.hibernate: debug
    root: info

# Server configuration
server:
  port: 8888
  tomcat:
    max-connections: 20
    threads:
      max: 5

---

# Dev profile
spring:
  profiles:
    active: dev
    include: "default"
  application:
    name: dev-app

  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password

---

# Prod profile
spring:
  profiles:
    active: prod
    include: "default"
  application:
    name: prod-app

  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password